#ifndef ACTION_H
#define	ACTION_H


enum	EAction
{
	SECONDARY_FIRE,
	CHANGE_WEAPON,

	// Thrust things
	A_THRUST_DEFAULT,
	A_THRUST_ALONG,
	A_THRUST_UP,
	A_TOGGLE_TRACTOR,

	// racer things
	A_RACER_ALONG,
	A_RACER_BOOST_START,
	A_RACER_BOOST_END,

	A_DIRECT_JUMP,
	A_DIRECT_ATTACK0,
	A_DIRECT_TRICK0,
	A_DIRECT_START_BLOCK,
	A_DIRECT_END_BLOCK,
	A_DIRECT_THROW,
	A_DIRECT_SPIN_ATTACK,
	A_DIRECT_START_RACER_BOOST  // at start of race
};

#endif