#ifndef PSXFMV_H
#define PSXFMV_H

#include	"movie.h"

enum	EMovie
{
	FMV_ROCKSTAR = 0,
	FMV_LOSTTOYS,
	FMV_BROADSWORD,
	FMV_INTRO_ENG,
	FMV_INTRO_FRE,
	FMV_INTRO_GER,
	FMV_INTRO_SPA,
	FMV_INTRO_ITA,
	FMV_ANGEL,
	FMV_APOSTLE,
	FMV_BENNY,
	FMV_LOCKDOWN,
	FMV_SOPHIE,
	FMV_DOCTOR,
	FMV_ALPHASTAR_IN,
	FMV_ALPHASTAR_ANGEL,
	FMV_ALPHASTAR_APOSTLE,
	FMV_ALPHASTAR_BENNY,
	FMV_ALPHASTAR_LOCKDOWN,
	FMV_ALPHASTAR_SOPHIE,
	FMV_ALPHASTAR_DOCTOR,
};

extern	SINT	PlayFMV(EMovie movie);

#endif