// $Header$

// $Log$
// Revision 1.2  2000-07-11 10:30:58+01  jjs
// Put back to original Lost Toys version.
//

#ifndef OIDS_H
#define OIDS_H

//  these *NEVER* change


#define	MAX_OIDS	2048

enum
{
	OID_INVALID					= -2,
	OID_NONE					= -1,
	OID_CThing					= 0,
	OID_CActor					= 1,
	OID_CEffector				= 2,
	OID_CEFRainDrop				= 3,
	OID_CEFLineWaveYR			= 4,	// dead
	OID_CSpawner				= 5,
	OID_CSpawnerBall			= 6,	// dead
	OID_CSpawnerDrone			= 7,	// dead
//	OID_CDrone					= 8,
	OID_CPrimary				= 9,
	OID_CFinish					= 10,
	OID_CSpikes					= 11,
	OID_CEffect					= 12,
	OID_CFXLightning			= 13,
	OID_CMorph					= 14,
	OID_CMPBomb					= 15,
	OID_CMPAverage				= 16,
	OID_CPickup					= 17,
	OID_CPickupStatic			= 18,
	OID_CTrigger				= 19,
	OID_CFollower				= 20,	// dead
	OID_CSpawnerFollower		= 21,	// dead
//	OID_CDrawbridge				= 22,
//	OID_CWall					= 23,
	OID_CStaticMesh				= 24,
//	OID_CSMCastle				= 25,
	OID_CCannon					= 29,
	OID_CCannonBall				= 30,
	OID_CMPLower				= 31,
//	OID_CSMTower1				= 32,
//	OID_CSMTower2				= 33,
//	OID_CSMTower3				= 34,
//	OID_CSMWindmill				= 35,
//	OID_CSMWindmillBlades		= 36,
//	OID_CKnight					= 37,
//	OID_CSolid					= 38,
//	OID_CLift					= 39,
//	OID_CCatapault				= 40,
//	OID_CLiftRight1				= 41,
//	OID_CSMTree1				= 42,
//	OID_CSMTree2				= 43,
	OID_CSMShipViking			= 44,	// dead
	OID_CSMShipPirate			= 45,	// dead
	//OID_CFlipper				= 46,
	//OID_CFlipperRight			= 47,
	//OID_CFlipperLeft			= 48,
	OID_CTeleport				= 49,
	OID_CCharacter				= 50,
	//OID_CFollower1				= 51,	// dead
	//OID_CFollower2				= 52,	// dead
	//OID_CFollower3				= 53,   // dead
	//OID_CFollower4				= 54,   // dead
	OID_CFXFlamer				= 55,
	OID_CEFLineWavePair			= 56,
	OID_CSMBoat					= 57,	// dead
	OID_CNurbling				= 58,	// dead
	OID_CNurbling1				= 59,	// dead
	OID_CNurbling2				= 60,	// dead
	OID_CNurbling3				= 61,	// dead
	OID_CNurbling4				= 62,	// dead
	OID_CFlameThrower			= 63,
	OID_CFlameThrowerBase		= 64,	// dead
	OID_CPUPBrake				= 65,
	OID_CPUPToken				= 66,
//	OID_CSpikyDeath				= 67,	// dead
	OID_CCharBall				= 68,
//	OID_CClown					= 69,	// dead
	OID_CEffectParticle			= 70,
//	OID_CFXZ					= 71,	// dead
	OID_CVampire				= 72,	// dead
	OID_CPumpkinHead			= 73,	// dead
	OID_CViking					= 74,	// dead
	OID_CCowboy					= 75,	// dead
	OID_CGhost					= 76,	// dead
//	OID_CCharNoBall				= 77,	// dead
//	OID_CJack					= 78,	// dead
	OID_CSMArrowL				= 79,
	OID_CSMArrowR				= 80,
	OID_CFinishPin				= 81,
	OID_CZombie					= 82,	// dead
//	OID_CBlimp					= 83,
	OID_CNurbling5				= 84,	// dead
	OID_CGuardB					= 85,
	OID_CGuardA					= 86,
	OID_CSGuardC				= 87,
	OID_CNurblingA				= 88,	// dead
	OID_CNurblingA1				= 89,	// dead
	OID_CNurblingA2				= 90,	// dead
	OID_CNurblingA3				= 91,	// dead
	OID_CNurblingA4				= 92,	// dead
	OID_CDictator				= 93,	// dead
	OID_CRobot					= 94,	// dead
	OID_COfficer				= 95,	// dead
	OID_CSoldier1				= 96,	// dead
	OID_CTank					= 97,	// dead
	OID_CDcTank					= 98,	// dead
//	OID_CSMMTree1				= 99,
//	OID_CSMMTree2				= 100,
//	OID_CSMMTree3				= 101,
//	OID_CSMMTree4				= 102,
//	OID_CSMMTree5				= 103,
//	OID_CSMMTree6				= 104,
	OID_CSMHwTower1				= 105,	// dead
	OID_CSMHwHouse				= 106,	// dead
	OID_CSMHwTomb				= 107,	// dead
	OID_CSMHwHotel				= 108,	// dead
	OID_CSMHwGraves				= 109,	// dead
	OID_CSMHwCastle				= 110,	// dead
	OID_CSMMechBossTower		= 111,	// dead
	OID_CSMVacuumCannon			= 112,	// dead
	OID_CSMHwChurch				= 113,	// dead
	OID_CSMHwOrgan				= 114,	// dead
	OID_CHwDoc					= 115,	// dead
	OID_CWayPoint				= 116,
	OID_CNamedMesh				= 117,
	OID_CBoat					= 118, // dead
	OID_CBoatViking				= 119, // dead
	OID_CBoatPirate				= 120, // dead
	OID_CRacer					= 121,
	OID_CRacerTank				= 122,
	OID_CRacerGhost				= 123,
	//OID_CMechCatapault			= 124,
//	OID_CFlyDroid				= 125,
	//OID_CSteamHammer			= 126,
	OID_CEFLineWavePair2		= 127,
	OID_CProjectile				= 128,
	OID_CPJBullet				= 129,
	OID_CPrimaryChar			= 130,
	OID_CGolfArrow				= 131,
	OID_CGunTurret				= 132,
	OID_CBadGuy					= 133,
	OID_CPJBulletRainDrop		= 134,
	OID_CPrimaryBall			= 135,
	OID_CTriggerTile			= 136,
	OID_CTriggerDead			= 137,
	OID_CTriggerSwitch			= 138,
	OID_CSwitch					= 139,
	OID_CSwitchDead				= 140,
	OID_CSwitchAND				= 141,
	OID_CSwitchOR				= 142,
	OID_CPrimaryAngel			= 143,
	OID_CPrimaryApostle			= 144,
	OID_CPrimaryLockdown		= 145,
	OID_CGenerator				= 146,
	OID_CPUPHealth				= 147,
	OID_CWeapon					= 148,
	OID_CWeaponAngelSword		= 149,
	OID_CLaserTurret			= 150,
	OID_CCrate					= 151,
	OID_CFXFlamer2				= 152,
	OID_CFXFlamer3				= 153,
	OID_CFXStreamer				= 154,
	OID_CFlameThrowerGround		= 155,
	OID_CPrimaryAngelTorso		= 156,
	OID_CPrimaryApostleTorso	= 157,
	OID_CPrimaryLockdownTorso	= 158,
	OID_CGuardBTorso			= 159,
	OID_CGuardATorso			= 160,
	OID_CSGuardCTorso			= 161,
	OID_CTorso					= 162,
	OID_CFencePost				= 163,
	OID_CFenceSection			= 164,
	OID_CCannon2				= 165,
	OID_CPrimaryBenny			= 166,
	OID_CPrimaryBennyTorso		= 167,
	OID_CClownTorso				= 168,
	OID_CPrimarySophie			= 169,
	OID_CPrimarySophieTorso		= 170,
	OID_CKingHillGoalPoint		= 171,
	OID_CCheckPoint				= 172,
	OID_CCheckPointSection		= 173,
	OID_CTriggerLap				= 174,
	OID_CWeaponApostleSword		= 175,
	OID_CWeaponClub				= 176,
	OID_CWeaponCowProd			= 177,
	OID_CWeaponDagger			= 178,
	OID_CWeaponHammer			= 179,
	OID_CPrimaryDoctor			= 180,
	OID_CPrimaryDoctorTorso		= 181,
	OID_CThingSpawner			= 182,
	OID_CPrisoner1AKingHill		= 183,
	OID_CKingHillBadGuy			= 184,
	OID_CPrisoner2AKingHill		= 185,
	OID_CPrisoner3AKingHill		= 186,
	OID_CEditorLight			= 187,
	OID_CStartP1				= 188,
	OID_CStartP2				= 189,
	OID_CPathFinderPoint		= 190,
	OID_CHoldingZonePoint		= 191,
	OID_CHoldableThing			= 192,
//	OID_CGrenade				= 193,
	OID_CDeputy					= 194,
	OID_CMarshall				= 195,
	OID_CPrisoner1A				= 196,
	OID_CPrisoner2A				= 197,
	OID_CPrisoner3A				= 198,
	OID_CDeputyTorso			= 199,
	OID_CMarshallTorso			= 200,
	OID_CPrisoner1ATorso		= 201,
	OID_CPrisoner2ATorso		= 202,
	OID_CPrisoner3ATorso		= 203,
	OID_CFXExplosion1			= 204,
	OID_CPrisoner1B				= 205,
	OID_CPrisoner1BTorso		= 206,
	OID_CPrisoner1C				= 207,
	OID_CPrisoner1CTorso		= 208,
	OID_CTriggerScore			= 209,
	OID_CFXExplosion2			= 210,
	OID_CDroidBallDispenser		= 211,
	OID_CDroidBall				= 212,
	OID_CDroidBallPot			= 213,

	OID_CPrisoner2B				= 214,
	OID_CPrisoner2C				= 215,
	OID_CPrisoner3B				= 216,
	OID_CPrisoner3C				= 217,
	OID_CPrisoner2BTorso		= 218,
	OID_CPrisoner2CTorso		= 219,
	OID_CPrisoner3BTorso		= 220,
	OID_CPrisoner3CTorso		= 221,
	OID_CGuardC					= 222,
	OID_CSGuardA				= 223,
	OID_CSGuardB				= 224,
	OID_CGuardCTorso			= 225,
	OID_CSGuardATorso			= 226,
	OID_CSGuardBTorso			= 227,
	OID_CHealthTile				= 228,
	OID_CFXBodyFlamer			= 229,
	OID_CCrown					= 230,
	OID_CLaserBeam				= 231,
	OID_CBallDispenser			= 232,
//	OID_CGrenadeDispenser		= 233,
	OID_CBadGuyLockDown			= 234,
	OID_CBadGuyPrimary			= 235,
	OID_CBadGuyApostle			= 236,
	OID_CBadGuyBenny			= 237,
	OID_CBadGuySophie			= 238,
	OID_CBadGuyDoctor			= 239,
	OID_CBadGuyAngel			= 240,
	OID_CHovBot					= 241,
	OID_CFXTeleportIn			= 242,
	OID_CFXRageAttack			= 243,
	OID_CFinishTrigger			= 244,
	OID_CSMBillBoard			= 245,
	OID_CPit					= 246,
	OID_CGillam					= 247,
	OID_CGillamTorso			= 248,
	OID_CStinger				= 249,
	OID_CSMWaterTower			= 250,
	OID_CSMLitTower				= 251,
	OID_CSMGolfBoard			= 252,
	OID_CSMIcon					= 253,
	OID_CSMStatue				= 254,
	OID_CSMVase					= 255,
	OID_CTVCamera				= 256,
	OID_CSMChevron				= 257,
	OID_CSMChevrons				= 258,
//	OID_CKingHillBadGuyLockDown	= 259,
//	OID_CKingHillBadGuyPrimary	= 260,
//	OID_CKingHillBadGuyApostle	= 261,
//	OID_CKingHillBadGuyBenny	= 262,
//	OID_CKingHillBadGuySophie	= 263,
//	OID_CKingHillBadGuyDoctor	= 264,
//	OID_CKingHillBadGuyAngel	= 265,
	OID_CRacerReSpawner			= 266,
	OID_CTriggerOnePrimaryOnHill= 267,
	OID_EOL,
};


class CThing;

CThing	*SpawnThing(SINT id, BOOL report_errors = TRUE);
BOOL	CanThisOIDBeInstantiated(SINT id);

#endif
