//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Configpanel.rc
//
#define IDD_CONFIGURATION               101
#define IDD_MAP_KEYBOARD                101
#define IDD_START                       103
#define IDD_VIDEO_SOUND                 104
#define IDD_CONTROLLER                  105
#define IDB_ENGLISH_LOGO                105
#define IDD_MAP_JOYSTICK                106
#define IDC_CONFIGURE                   1000
#define IDC_COMBO1                      1004
#define IDC_DISPLAY_DEVICE_LIST         1004
#define IDC_VIDEO_SOUND_DISPLAY_DEVICE_LIST 1004
#define IDC_CONTROLLER_PLAYERONE_CONTROLLER_LIST 1004
#define IDC_VIDEO_DEVICE                1005
#define IDC_VIDEO_SOUND_VIDEO_DEVICE_CAPTION 1005
#define IDC_CONTROLLER_PLAYERTWO_CONTROLLER_LIST 1005
#define IDC_COMBO2                      1006
#define IDC_RESOLUTION_LIST             1006
#define IDC_VIDEO_SOUND_RESOLUTION_LIST 1006
#define IDC_INGAME_RES                  1007
#define IDC_VIDEO_SOUND_RESOLUTION_CAPTION 1007
#define IDC_VIDEO_OPTIONS               1008
#define IDC_VIDEO_SOUND_VIDEO_OPTIONS   1008
#define IDC_SOUND_OPTIONS               1009
#define IDC_VIDEO_SOUND_SOUND_OPTIONS   1009
#define IDC_SOUND_DEVICE_LIST           1010
#define IDC_VIDEO_SOUND_SOUND_DEVICE_LIST 1010
#define IDC_SOUND_DEVICE_CAPTION        1011
#define IDC_VIDEO_SOUND_SOUND_DEVICE_CAPTION 1011
#define IDC_INPUT_OPTIONS1              1012
#define IDC_ACTION_CAPTION              1013
#define IDC_MAP_KEYBOARD_ACTION_CAPTION 1013
#define IDC_KEY_MAPPING                 1014
#define IDC_MAP_KEYBOARD_KEY_CAPTION    1014
#define IDC_ACTION1                     1015
#define IDC_MAP_KEYBOARD_ACTION1        1015
#define IDC_INPUT_OPTIONS2              1016
#define IDC_ACTION_CAPTION2             1017
#define IDC_ACTION5                     1018
#define IDC_MAP_KEYBOARD_ACTION5        1018
#define IDC_MAPPING1                    1019
#define IDC_ACTION2                     1020
#define IDC_MAP_KEYBOARD_ACTION2        1020
#define IDC_MAPPING2                    1021
#define IDC_ACTION3                     1022
#define IDC_MAP_KEYBOARD_ACTION3        1022
#define IDC_MAPPING3                    1023
#define IDC_ACTION4                     1024
#define IDC_MAP_KEYBOARD_ACTION4        1024
#define IDC_MAPPING4                    1025
#define IDC_MAPPING5                    1026
#define IDC_ACTION6                     1027
#define IDC_MAP_KEYBOARD_ACTION6        1027
#define IDC_ACTION7                     1028
#define IDC_MAP_KEYBOARD_ACTION7        1028
#define IDC_ACTION8                     1029
#define IDC_MAP_KEYBOARD_ACTION8        1029
#define IDC_MAPPING6                    1030
#define IDC_MAPPING7                    1031
#define IDC_MAPPING8                    1032
#define IDC_ACTION9                     1033
#define IDC_MAPPING9                    1034
#define IDC_KEY_MAPPING2                1035
#define IDC_ACTION10                    1036
#define IDC_MAP_KEYBOARD_ACTION10       1036
#define IDC_MAP_KEYBOARD_ACTION9        1036
#define IDC_MAPPING10                   1037
#define IDC_ACTION11                    1038
#define IDC_ACTION12                    1039
#define IDC_ACTION13                    1040
#define IDC_MAPPING11                   1041
#define IDC_MAPPING12                   1042
#define IDC_START_INSTALL               1042
#define IDC_MAPPING13                   1043
#define IDC_START_PLAY                  1043
#define IDC_MAP_KEYBOARD_CAPTION        1043
#define IDC_MAPPING14                   1044
#define IDC_START_DEVICE_OPTIONS        1044
#define IDC_MAP_JOYSTICK_CAPTION        1044
#define IDC_MAPPING15                   1045
#define IDC_START_CONTROLLER_OPTIONS    1045
#define IDC_CONTROLLER_PLAYERTWO_CAPTION 1045
#define IDC_MAPPING16                   1046
#define IDC_START_UNINSTALL             1046
#define IDC_CONTROLLER_PLAYERONE_CAPTION 1046
#define IDC_MAPPING17                   1047
#define IDC_START_QUIT                  1047
#define IDC_CONTROLLER_RUN_GAME_OPTIONS_PANEL 1047
#define IDC_MAPPING18                   1048
#define IDC_CONTROLLER_OK               1048
#define IDC_ACTION14                    1049
#define IDC_CONTROLLER_CANCEL           1049
#define IDC_ACTION15                    1050
#define IDC_CONTROLLER_CONFIGURE_PLAYERONE_DEVICE 1050
#define IDC_ACTION16                    1051
#define IDC_CONTROLLER_CONFIGURE_PLAYERTWO_DEVICE 1051
#define IDC_ACTION17                    1052
#define IDC_ACTION18                    1053
#define IDC_MAP_JOYSTICK_ACTION_CAPTION 1062
#define IDC_MAP_JOYSTICK_ACTION_CAPTION1 1062
#define IDC_MAP_JOYSTICK_AXES_CAPTION   1063
#define IDC_MAP_JOYSTICK_ACTION1        1064
#define IDC_MAP_JOYSTICK_ACTION2        1065
#define IDC_MAP_JOYSTICK_BUTTON_CAPTION 1066
#define IDC_MAP_JOYSTICK_ACTION_CAPTION2 1067
#define IDC_MAP_JOYSTICK_ACTION5        1068
#define IDC_MAP_JOYSTICK_ACTION6        1069
#define IDC_MAP_JOYSTICK_ACTION7        1070
#define IDC_MAP_JOYSTICK_ACTION8        1071
#define IDC_MAP_JOYSTICK_ACTION10       1073
#define IDC_MAP_JOYSTICK_ACTION9        1073
#define IDC_MAP_JOYSTICK_OK             1074
#define IDC_MAP_JOYSTICK_CANCEL         1075
#define IDC_MAP_KEYBOARD_OK             1076
#define IDC_MAP_KEYBOARD_CANCEL         1077
#define IDC_VIDEO_SOUND_OK              1078
#define IDC_VIDEO_SOUND_CANCEL          1079
#define IDC_CONTROLLER_PLAYERONE_CONTROL_DEVICE_CAPTION 1080
#define IDC_CONTROLLER_PLAYERTWO_CONTROL_DEVICE_CAPTION 1081
#define IDC_MAP_JOYSTICK_RUN_GAME_OPTIONS_PANEL 1081
#define IDC_MAP_JOYSTICK_RUN_GAME_OPTIONS_PANEL2 1082
#define IDC_MAP_JOYSTICK_MAPPING1       1083
#define IDC_MAP_JOYSTICK_MAPPING2       1084
#define IDC_MAP_KEYBOARD_MAPPING1       1084
#define IDC_MAP_JOYSTICK_MAPPING3       1085
#define IDC_MAP_KEYBOARD_MAPPING2       1085
#define IDC_MAP_JOYSTICK_MAPPING4       1086
#define IDC_MAP_KEYBOARD_MAPPING3       1086
#define IDC_MAP_JOYSTICK_MAPPING5       1087
#define IDC_MAP_KEYBOARD_MAPPING4       1087
#define IDC_MAP_JOYSTICK_MAPPING6       1088
#define IDC_MAP_KEYBOARD_MAPPING5       1088
#define IDC_MAP_JOYSTICK_MAPPING7       1089
#define IDC_MAP_KEYBOARD_MAPPING6       1089
#define IDC_MAPPING19                   1090
#define IDC_MAP_KEYBOARD_MAPPING7       1090
#define IDC_MAP_KEYBOARD_MAPPING8       1091
#define IDC_MAP_KEYBOARD_MAPPING9       1092
#define IDC_ACTION19                    1095
#define IDC_MAPPING20                   1096
#define IDC_ACTION20                    1097
#define IDC_PRODUCT_VERSION             -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        106
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1085
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
